---

- name: "Ensure firewalld service is running"
  systemd:
    state: started
    name: firewalld
    enabled: yes

- name: "Open Firewall for Role." 
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items: "{{ rh_ports }}"
