apiVersion: v1
kind: Service
metadata:
  namespace: {{QUAY_NAMESPACE}}
  name: quay-enterprise-clusterip
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 8443
  selector:
    quay-enterprise-component: app