apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{QUAY_NAMESPACE}}
  name: {{QUAY_APP_NAME}}
  labels:
    quay-enterprise-component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      quay-enterprise-component: app
  template:
    metadata:
      namespace: {{QUAY_NAMESPACE}}
      labels:
        quay-enterprise-component: app
    spec:
      volumes:
      - name: configvolume
        secret:
          secretName: {{QUAY_SECRET_NAME}}
    containers:
     - name: {{QUAY_APP_NAME}}
       image: {{QUAY_IMAGE}}
       ports:
        - containerPort: 8443
          volumeMounts:
        - name: configvolume
          readOnly: false
          mountPath: /conf/stack
    imagePullSecrets:
     - name: redhat-quay-pull-secret